### ISSUE TITLE
Question: Bar graph generator or histogram?

### ISSUE THREAD

**Issue by garthwebb** [tj/histo#11]
This seems to generate a single bar for every data element in the input file, essentially a bar graph generator.  A histogram buckets the data into groups (0 - 10 == bucket 1, 11 - 20 == bucket 2, etc) and then plots bars for every bucket giving you a idea of the distribution of the values in your dataset.

**Comment by tj** [comment]
yeah you're right :( not sure what a nice name would be, baro haha

**Comment by livibetter** [comment]
I was confused when I saw the chart and example data, too.

> Plot _histograms_ in the terminal with arbitrary streaming or non-streaming data.

You need to at least replace "[histograms](http://en.wikipedia.org/wiki/Histogram)" with _[bar chart](http://en.wikipedia.org/wiki/Bar_chart)_, because **histo** is plotting bar chart not histogram, they have huge difference and usage. The project name is okay to keep, though definitely mess up with people who knows what histogram is, but you never know someday someone might add real histogram chart to histo.

**Comment by tj** [comment]
tweaked the docs, we could have several modes later on so it can actually be have as a histogram instead of preprocessing the data

**Comment by livibetter** [comment]
@visionmedia since you mentioned "docs" and you used "histo(1)" in Readme, I guess there is manpage, but you forget to add it or them?
